### ISSUE TITLE
query service

### ISSUE THREAD

**Issue by fntz** [scalalab3/logs-service#17]
https://github.com/scalalab3/logs-service/wiki/overview

1. сервис должен быть актором

2. конвертировать пользовательский запрос в АСТ ресинка и возвращать результат, в случае некоректного запроса сервис отдаёт 400 Bad Request  

3 (адванс). должа быть удобная работа с датами и промежутками, вернуть данные за последние N минут\часов, вернуть данные в промежутке: 15 minutes..30minutes AND message contains "foo" 

4. хттп роутер должен работать со следующим запросом `query="query string"`

**Comment by fntz** [comment]
здесь делал Антон и Антон, не?

**Comment by fntz** [comment]
cc @m00t

**Comment by m00t** [comment]
@fntz изначально думали делать я и Сергей (myk1987_ в скайпе).

**Comment by fntz** [comment]
а извини перепутал, Сергей вроде свалил не?

**Comment by m00t** [comment]
Антон уже много чего сделал, может быть он и продолжит?

**Comment by m00t** [comment]
Ушел не тот Сергей если что =)

**Comment by fntz** [comment]
без проблем.
